spring.application.name=userService
server.port=${SERVER_PORT}
# Note, dok ne dokerizujemo ovo moramo definisati fallback vrednosti kao ${VARIJABLA:zapravoVrednost}
# Security
jwt.secret=${JWT_SECRET}
banka.security.issuer=banka1
banka.security.id=id
banka.security.roles-claim=roles
#ms
banka.security.expiration-time=3600000
#months
token.refresh.expiration-time=1
#minutes
token.confirmation.expiration-time=15
banka.security.permissions-claim=permissions
banka.security.permit-all=/auth/*,/v3/api-docs/**,/v3/api-docs.yaml,/swagger-ui/**,/swagger-ui.html,/actuator/**
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
server.forward-headers-strategy=FRAMEWORK
url.reset-password=${USER_RESET_PASSWORD_URL:http://localhost:3000/reset-password?token=}
url.activate-account=${USER_ACTIVATE_ACCOUNT_URL:http://localhost:3000/activate?token=}
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.queue=${NOTIFICATION_QUEUE}
rabbitmq.exchange=${NOTIFICATION_EXCHANGE}
rabbitmq.routing-key=${NOTIFICATION_ROUTING_KEY}
# Database konekcija (dok ne dokerizujemo ovo moraju biti fallback vrednosti posle :)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Liquibase hendluje ddl operacije, hibernate samo validira i baca gresku ako se nesto ne uklapa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
