spring.application.name=userService
server.port=${SERVER_PORT}
# Note, dok ne dokerizujemo ovo moramo definisati fallback vrednosti kao ${VARIJABLA:zapravoVrednost}
# Security
jwt.secret=${JWT_SECRET}

banka.security.issuer=banka1
banka.security.id=id
banka.security.roles-claim=roles
#ms
banka.security.expiration-time=3600000
#months
token.refresh.expiration-time=1
#minutes
token.confirmation.expiration-time=15


banka.security.permissions-claim=permissions
banka.security.permit-all=/auth/*,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html

url.reset-password="http://localhost:4200/auth/reset-password?token="
url.activate-account="http://localhost:4200/auth/activate-account?token="

management.endpoints.web.exposure.include=*


spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

rabbitmq.queue=emailQueue
rabbitmq.exchange=email
rabbitmq.routing-key=email.send


# Database konekcija (dok ne dokerizujemo ovo moraju biti fallback vrednosti posle :)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase hendluje ddl operacije, hibernate samo validira i baca gresku ako se nesto ne uklapa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
