spring.application.name=userService
server.port=${SERVER_PORT:8081}
# Note, dok ne dokerizujemo ovo moramo definisati fallback vrednosti kao ${VARIJABLA:zapravoVrednost}
# Security
jwt.secret=${JWT_SECRET:OvoJeNekaDugackaTajnaSifraZaJwtKojuNeStavljamoUProperties}
banka.security.roles-claim=roles
banka.security.permissions-claim=permissions
banka.security.permit-all=/auth/*,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html

url.reset-password="http://localhost:4200/auth/reset-password?token="
url.activate-account="http://localhost:4200/auth/activate-account?token="

management.endpoints.web.exposure.include=*


spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:rabbit}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:rabbit}

rabbitmq.queue=emailQueue
rabbitmq.exchange=email
rabbitmq.routing-key=email.send


# Database konekcija (dok ne dokerizujemo ovo moraju biti fallback vrednosti posle :)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banka}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase hendluje ddl operacije, hibernate samo validira i baca gresku ako se nesto ne uklapa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
