CREATE TABLE exchange_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3) NOT NULL,
    buying_rate NUMERIC(19, 8) NOT NULL,
    selling_rate NUMERIC(19, 8) NOT NULL,
    rate_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_exchange_rate_currency_date UNIQUE (currency_code, rate_date),
    CONSTRAINT chk_exchange_rate_buying_positive CHECK (buying_rate > 0),
    CONSTRAINT chk_exchange_rate_selling_positive CHECK (selling_rate > 0)
);

CREATE INDEX idx_exchange_rate_rate_date ON exchange_rate (rate_date);
CREATE INDEX idx_exchange_rate_currency_code ON exchange_rate (currency_code);
