spring.application.name=accountService
server.port=${ACCOUNT_SERVER_PORT}
# Note, dok ne dokerizujemo ovo moramo definisati fallback vrednosti kao ${VARIJABLA:zapravoVrednost}
# Security
banka.security.issuer=banka1
banka.security.id=id
banka.security.roles-claim=roles
#ms
banka.security.expiration-time=3600000
#months
token.refresh.expiration-time=1
#minutes
token.confirmation.expiration-time=15
banka.security.permissions-claim=permissions
banka.security.permit-all=/auth/*,/v3/api-docs/**,/v3/api-docs.yaml,/swagger-ui/**,/swagger-ui.html,/actuator/**
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
server.forward-headers-strategy=FRAMEWORK
url.reset-password="http://localhost:4200/auth/reset-password?token="
url.activate-account="http://localhost:4200/auth/activate-account?token="
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true

jwt.secret=${JWT_SECRET}
my.random.seed=1

#todo ubaciti u env
services.user.url=${SERVICES_USER_URL}:${CLIENT_SERVER_PORT}
services.card.url=${SERVICES_CARD_URL:http://localhost:8085}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.queue=${NOTIFICATION_QUEUE}
rabbitmq.exchange=${NOTIFICATION_EXCHANGE}
rabbitmq.routing-key=${NOTIFICATION_ROUTING_KEY}
# Database konekcija (dok ne dokerizujemo ovo moraju biti fallback vrednosti posle :)
spring.datasource.url=jdbc:postgresql://${ACCOUNT_DB_HOST}:${ACCOUNT_DB_PORT}/${ACCOUNT_DB_NAME}
spring.datasource.username=${ACCOUNT_DB_USER}
spring.datasource.password=${ACCOUNT_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Liquibase hendluje ddl operacije, hibernate samo validira i baca gresku ako se nesto ne uklapa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#ovo otkomentarisati samo kada brises
#spring.liquibase.drop-first=true
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate=ERROR



