spring.application.name=verificationService
server.port=${VERIFICATION_SERVER_PORT}

# Security
banka.security.issuer=banka1
banka.security.id=id
banka.security.roles-claim=roles
#ms
banka.security.expiration-time=3600000
#months
token.refresh.expiration-time=1
#minutes
token.confirmation.expiration-time=5
banka.security.permissions-claim=permissions
banka.security.permit-all=/v3/api-docs/**,/v3/api-docs.yaml,/swagger-ui/**,/swagger-ui.html,/actuator/**

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.config-url=/verification/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/verification/v3/api-docs
server.forward-headers-strategy=FRAMEWORK

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
management.endpoint.health.show-details=never
management.endpoint.health.group.readiness.include=readinessState,db,rabbit

jwt.secret=${JWT_SECRET}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.exchange=${NOTIFICATION_EXCHANGE}
rabbitmq.routing-key=${NOTIFICATION_ROUTING_KEY}
rabbitmq.routing-key.verification=${NOTIFICATION_VERIFICATION_ROUTING_KEY:client.verification}

# Database
spring.datasource.url=jdbc:postgresql://${VERIFICATION_DB_HOST}:${VERIFICATION_DB_PORT}/${VERIFICATION_DB_NAME}
spring.datasource.username=${VERIFICATION_DB_USER}
spring.datasource.password=${VERIFICATION_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase handles DDL, Hibernate only validates
spring.jpa.hibernate.ddl-auto=validate
# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

company.observability.starter.user-id-mdc-enabled=true
