version: "3.9"

services:
  postgres_account:
    image: postgres:15
    container_name: postgres_account
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
      POSTGRES_USER: ${ACCOUNT_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
    ports:
      - "${ACCOUNT_DB_EXTERNAL_PORT}:${ACCOUNT_DB_INTERNAL_PORT}"
    volumes:
      - postgres_account_data:/var/lib/postgresql/data
    networks:
      - banka-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    networks:
      - banka-network

#  account-service:
#    build:
#      context: ..
#      dockerfile: account-service/Dockerfile
#    container_name: account-service
#    restart: unless-stopped
#    depends_on:
#      - postgres_account
#      - rabbitmq
#    environment:
#      SERVER_PORT: ${ACCOUNT_SERVER_PORT}
#      DOCKER_PORT: ${ACCOUNT_DOCKER_PORT}
#
#      ACCOUNT_DB_HOST: ${ACCOUNT_DB_HOST}
#      ACCOUNT_DB_PORT: ${ACCOUNT_DB_PORT}
#      ACCOUNT_DB_NAME: ${ACCOUNT_DB_NAME}
#      ACCOUNT_DB_USER: ${ACCOUNT_DB_USER}
#      ACCOUNT_DB_PASSWORD: ${ACCOUNT_DB_PASSWORD}
#
#      SERVICES_USER_URL: ${SERVICES_USER_URL}
#
#      RABBITMQ_HOST: ${RABBITMQ_HOST}
#      RABBITMQ_PORT: ${RABBITMQ_PORT}
#      RABBITMQ_MANAGEMENT_PORT: ${RABBITMQ_MANAGEMENT_PORT}
#      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
#      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#      RABBITMQ_LISTENER_ENABLED: ${RABBITMQ_LISTENER_ENABLED}
#
#      JWT_SECRET: ${JWT_SECRET}
#
#      LOG_LEVEL_ROOT: ${LOG_LEVEL_ROOT}
#      LOG_LEVEL_APP: ${LOG_LEVEL_APP}
#    ports:
#      - "${ACCOUNT_DOCKER_PORT}:${ACCOUNT_SERVER_PORT}"
#    networks:
#      - banka-network

volumes:
  postgres_account_data:

networks:
  banka-network:
    driver: bridge