FROM gradle:8.14.3-jdk21-alpine AS builder

WORKDIR /app

COPY account-service ./account-service
COPY security-lib ./security-lib
COPY company-observability-starter ./company-observability-starter

WORKDIR /app/account-service

RUN gradle build --no-daemon -x test -x checkstyleMain -x checkstyleTest

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=builder /app/account-service/build/libs/*.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]